### ISSUE TITLE
Limit voting numbers

### ISSUE THREAD

**Issue by rav-andre** [Sintrop/core-contracts#109]
At this moment, we can vote as many tokens as wished in the ISA categories. 

This issue is to set a limit number, so one user can't vote more than this limit in each category.

We will further study and define properly this amount, but to start we can set this number in 100.000 (one hundred thousand) SAC tokens.

**Comment by everson-ever** [comment]
# Code Suggestion

`CategoryContract.sol` - Adding a constant to represent limit of votes

```solidity
contract CategoryContract {
  uint256 public constant LIMIT_VOTING = 100000000000000000000000;

  mapping(uint256 => Category) public categories;
  mapping(uint256 => uint256) public votes;
  mapping(address => mapping(uint256 => uint256)) public voted;

  //...other code
}
```

<br>


`CategoryContract.sol` - Adding modifier

```solidity
  modifier mustNotExceedLimitVoting(uint256 id, uint256 tokens) {
    require(voted[msg.sender][id] + tokens <= LIMIT_VOTING, "can't vote more than 100k tokens");
    _;
  }
```

<br>


`CategoryContract.sol` - Using modifier in `vote` method

```solidity
  function vote(uint256 id, uint256 tokens)
    public
    categoryMustExists(id)
    mustHaveSacToken(tokens)
    mustSendSomeSacToken(tokens)
    mustNotExceedLimitVoting(id, tokens)
    returns (bool)
  {
    // ...other code
  }
```


# How to

- [ ] Add a constant to represent limit votes
- [ ] Create and use a modifier to validade limite of votes
- [ ] Add specs
