### ISSUE TITLE
Limit ISA voting to registered users

### ISSUE THREAD

**Issue by rav-andre** [Sintrop/core-contracts#110]
At this moment, every token holder can vote in the ISA categories.

This issue is to limit this action to only registered users. Every userType must be able to vote, including Actvists, Producers, Developers, Contributors, Advisors, Investors and Researchers.

But a non registered SAC token wallet can't vote, they must registered as Investors first. 

### Code suggestion
Add a modifier in the addCategory function to require a valid userType.

**Comment by rav-andre** [comment]
@everson-ever estava pensando aqui sobre essa issue em ir pelo caminho de adicionar um modifier na função addCategory para fazer essa checagem. 

No UserContract já temos um modifier que faz isso:

```
  modifier mustBeValidType(UserType userType) {
    require(userType != UserType.UNDEFINED, "Invalid user type");
     _;
  }
} 
```
Acha que faz sentido esse caminho de tentar usar esse modifier ao invés de criar um?

**Comment by everson-ever** [comment]
# Code Suggestion

`UserContract.sol` - Add a method to check if user exists

```solidity
  function exists(address addr) public view returns (bool) {
    return users[addr] != UserType.UNDEFINED;
  }
```

<br>

`CategoryContract.sol` - Add UserContract in constructor

```solidity
import "./UserContract.sol";

contract CategoryContract {
  mapping(uint256 => Category) public categories;
  mapping(uint256 => uint256) public votes;
  mapping(address => mapping(uint256 => uint256)) public voted;

  ResearcherContract public researcherContract;
  UserContract public userContract;

  Category public category;
  uint256 public categoryCounts;
  PoolPassiveInterface internal isaPool;

  constructor(address _isaPoolAddress, address researcherContractAddress, address userContractAddress) {
    isaPool = PoolPassiveInterface(_isaPoolAddress);
    researcherContract = ResearcherContract(researcherContractAddress);
    userContract = UserContract(userContractAddress);
  }

  // ...other code
}
```

<br>

`CategoryContract.sol` - Add modifier

```solidity
  modifier requireUserExists() {
    require(userContract.exists(msg.sender), "Only registered users can vote");
    _;
  }

}
```

<br>


`CategoryContract.sol` - Use modifier

```solidity
  function vote(uint256 id, uint256 tokens)
    public
    requireUserExists
    categoryMustExists(id)
    mustHaveSacToken(tokens)
    mustSendSomeSacToken(tokens)
    returns (bool)
  {
  // other codes
  }
```

<br>

`migrations/2_deploy_contracts.js` - Update CategoryContract deploy

```javascript
  await deployer.deploy(CategoryContract, isaPool.address, researcherContract.address, userContract.address);
```

# How to

- [ ] Create a method in UserContract to check if user exists
- [ ] Add UserContract as parameter in CategoryContract
- [ ] Check if user exists on vote
- [ ] Add specs
