### ISSUE TITLE
Events search + events implementation

### ISSUE THREAD

**Issue by everson-ever** [Sintrop/core-contracts#121]
# Description

Seach how works events in solidity. The ideia is to undestand:

:warning: This issue dont generate a Pull request (add the result as comment here)

- How works
- Benefits
- Gas cost?

# How to

- [ ] Add in this issue
  - [ ] How works events
  - [ ] benefits
  - [ ] Gas cost?

**Comment by rav-andre** [comment]
Also implement events to be able to create newsfeed page
