### ISSUE TITLE
update activist inspections security

### ISSUE THREAD

**Issue by rav-andre** [Sintrop/core-contracts#45]
A new feature to only allow an activist to accept and inspection if he hasn't inspected the same producer previously.

The goal is to not allow the same person to audit the same producer, increasing system security.

We must update the _acceptInspection_ function to require that he hasn't already accepted one inspection from this producer

![image](https://user-images.githubusercontent.com/79549809/169336939-e1287d30-882a-439e-93f1-1ca714a85d8a.png)

**Comment by everson-ever** [comment]
### Man, segue uma sugestão de código

## How to

### Add new mapping in [Sintrop.sol](https://github.com/Sintrop/core-contracts/blob/main/contracts/Sintrop.sol)

```solidity
mapping(address => mapping(address => bool)) internal activistInspected;
```

### Add a modifier to require activist never inspected producer yet

```solidity
  modifier requireNotInspectedProducer(uint256 inspectionId) {
    Inspection memory inspection = inspections[inspectionId];

    require(
      !activistInspected[msg.sender][inspection.createdBy],
      "Already inspected this producer"
    );
    _;
  }
```


### Use the modifier in accept inspection function

```solidity
 function acceptInspection(uint256 inspectionId)
    public
    requireActivist
    requireInspectionExists(inspectionId)
    requireNotInspectedProducer(inspectionId)
    returns (bool)
  {
    code...
  }
```

# Update `activistInspected` mapping after activist realize inspection

```solidity
 function realizeInspection(uint256 inspectionId, IsaInspection[] memory _isas)
    public
    requireActivist
    requireInspectionExists(inspectionId)
    requireInspectionAccepted(inspectionId)
    requireInspectionOwner(inspectionId)
    returns (bool)
  {
    otherCode...

    activistInspected[msg.sender][inspection.createdBy] = true;

    return true;
  }
```


### Accptance

- [ ] Not allow activist inspect same producer
- [ ] Add specs
